### ISSUE TITLE
Official Unity Support on Native Platforms

### ISSUE THREAD

**Issue by Nico04** [snowballdigital/flutter-unity-view-widget#10]
Have you seen this? 
https://blogs.unity3d.com/2019/06/17/add-features-powered-by-unity-to-native-mobile-apps/

It's a very good news for your plugin don't you think? 
Thanks!

**Comment by JanOwiesniak** [comment]
@Nico04 thanks for bringing this up!

**Comment by juicycleff** [comment]
@Nico04 that is really interesting to support, but I believe it only supports fullscreen, which in most use cases, we just want to embed unity for carrying out some actions. But again would pay close attention to this. Like @JanOwiesniak said thanks for bringing this up.

**Comment by thomas-stockx** [comment]
It's actually just a new exported project architecture starting with Unity 2019.3. The "Unity only supports full screen" part was already fixed in version 0.13.4 of this plugin, and also applies on projects exported from Unity 2019.3!

I've added an updated Build.cs script to the repo in my pull request, under scripts/Editor/Build.cs which adds support for Unity 2019.3.
